# Generated by Django 5.2.5 on 2025-08-26 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedexercise",
            name="workout",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_workout",
                to="django_app.workout",
                verbose_name="Тренировка",
            ),
        ),
    ]
