# Generated by Django 5.2.5 on 2025-08-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factualapproach',
            options={'ordering': ('-id',), 'verbose_name': 'Подход ', 'verbose_name_plural': 'Фактические подходы'},
        ),
        migrations.AlterModelOptions(
            name='factualexecise',
            options={'ordering': ('-id',), 'verbose_name': 'Упражнение', 'verbose_name_plural': 'Фактические упражнения'},
        ),
        migrations.AlterModelOptions(
            name='plannedapproach',
            options={'ordering': ('-id',), 'verbose_name': 'Подход ', 'verbose_name_plural': 'Планированные подходы'},
        ),
        migrations.AlterModelOptions(
            name='plannedexecise',
            options={'ordering': ('-id',), 'verbose_name': 'Упражнение', 'verbose_name_plural': 'Планированные упражнения'},
        ),
    ]
