# Generated by Django 5.2.5 on 2025-08-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_factualapproach_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedapproach',
            name='count_approach',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='plannedapproach',
            name='execise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_execise', to='django_app.plannedexecise', verbose_name='Тренировка'),
        ),
    ]
