# Generated by Django 5.2.5 on 2025-08-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_plannedapproach_count_approach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Имя Упражнения')),
                ('description', models.TextField(blank=True, db_index=True, verbose_name='Описание упражнения')),
            ],
            options={
                'verbose_name': 'Упражнение ',
                'verbose_name_plural': 'Список упражнения',
                'ordering': ('-id',),
            },
        ),
        migrations.RenameModel(
            old_name='FactualExecise',
            new_name='FactualExercise',
        ),
        migrations.RenameModel(
            old_name='PlannedExecise',
            new_name='PlannedExercise',
        ),
    ]
